spring.application.name=Library_Mngt_demo

spring.datasource.url=jdbc:mysql://localhost:3306/library_mngt_demo
spring.datasource.username=root
spring.datasource.password=Rohit@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080