spring.application.name=micro-api-gateway-P02

server.port=8080

# Eureka register (eureka pr registry )
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Actuator register (admin ko btana )
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS

# Routes to service

# User-Service
spring.cloud.gateway.routes[0].id=micro-user-service-P02
spring.cloud.gateway.routes[0].uri=lb://MICRO-USER-SERVICE-P02
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Order-Service
spring.cloud.gateway.routes[1].id=micro-order-service-P02
spring.cloud.gateway.routes[1].uri=lb://MICRO-ORDER-SERVICE-P02
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**


spring.cloud.gateway.actuator.verbose.enabled=true

logging.level.root=debug
