spring.application.name=Employee_rel_demo

spring.datasource.url=jdbc:mysql://localhost:3306/jpa_rel_emp
spring.datasource.username=root
spring.datasource.password=Rohit@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true

server.port=8080