spring.application.name=File-service

server.port=8081

# register it on eureka server
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

#actuator know about this service
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS


# file storage path
file.storage.path=${user.home}/drive-storage/files

#file upload limit
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# cors config
spring.web.cors.allowed-origin=http://localhost:5173
spring.web.cors.allowed-method=GET,POST,PUT,DELETE,OPTION
spring.web.cors.allowed-header=*


